
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Sep 04 18:41:22 ART 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 7;
  public static final int GTEQ = 18;
  public static final int TYPE_BOOLEAN = 30;
  public static final int LKEY = 26;
  public static final int LBRACKET = 28;
  public static final int LTEQ = 17;
  public static final int UMINUS = 21;
  public static final int LPAREN = 24;
  public static final int SEMI = 22;
  public static final int CONTINUE = 33;
  public static final int FOR = 36;
  public static final int MINUS = 5;
  public static final int RPAREN = 25;
  public static final int NOT = 11;
  public static final int AND = 10;
  public static final int LT = 15;
  public static final int OR = 9;
  public static final int COMMA = 23;
  public static final int CLASS = 32;
  public static final int PLUSEQ = 19;
  public static final int EXTERN = 42;
  public static final int TYPE_INT = 39;
  public static final int MINUSEQ = 20;
  public static final int PLUS = 4;
  public static final int IF = 35;
  public static final int EOF = 0;
  public static final int RETURN = 40;
  public static final int RBRACKET = 29;
  public static final int TRUE = 43;
  public static final int RKEY = 27;
  public static final int error = 1;
  public static final int EQEQ = 14;
  public static final int MOD = 8;
  public static final int BREAK = 31;
  public static final int VOID = 41;
  public static final int TYPE_FLOAT = 38;
  public static final int EQ = 12;
  public static final int TIMES = 6;
  public static final int ELSE = 34;
  public static final int WHILE = 37;
  public static final int FALSE = 44;
  public static final int FLOAT_LITERAL = 3;
  public static final int GT = 16;
  public static final int INT_LITERAL = 2;
  public static final int NOTEQ = 13;
  public static final int IDENTIFIER = 45;
}

